---
title: "Predicting breast cancer from digitized images of breast mass"
author: "Tiffany A. Timbers </br>"
date: "2019/12/30 (updated: `r Sys.Date()`)"
output: 
  github_document:
    toc: true
bibliography: breast_cancer_references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(caret)
```

# Summary

# Introduction

# Methods

## Data
The data used to train and test the breast cancer predictive model was sourced from the UCI Machine Learning Repository [@Dua2019] and can be found [here](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic)). Only the following 10 variables were used in the analysis:

- area
- class
- compactness
- concave_points
- concavity
- fractal_dimension
- perimeter
- radius
- smoothness
- symmetry
- texture"

## Analysis
The k-nearest neighbors (k-nn) algorithm was used to build a classification model to predict whether a tumour mass was benign or malignant (found in the class column of the data set). The remaining 9 variables listed above were used as predictors in the model. The hyperparameter $K$ was chosen using 10-fold cross validation with overall classification accuracy as the loss function. The R and Python programming languages [@R; @Python] and the following R and Python packages were used to perform the analysis: caret [@caret], docopt [@docopt], feather [@feather], knitr [@knitr], tidyverse [@tidyverse], docopt [@docoptpython], os [@Python], feather [@feather] Pandas [@mckinney-proc-scipy-2010]. The code used to perform the analysis and create this report can be found here: https://github.com/ttimbers/breast_cancer_predictor.

# Results & Discussion

# References

